upstream backend {
    least_conn;

    server backend1:5000;
    server backend2:5000;
    server backend3:5000;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://backend;
    }

    location /admin/ {
        proxy_pass http://admin;
    }

    location / {
        proxy_pass http://frontend;
    }
}